### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'execute_script'

### ISSUE THREAD

**Issue by ktorq** [mintapi/mintapi#592]
It seems something has broke between 2.12 and 2.13 - the below code worked fine on 2.12
```
client = mintapi.Mint(keys['mint_user'], keys['mint_pw'], headless=False, wait_for_sync=False, mfa_method='authenticator')
transactions = pd.DataFrame(client.get_transaction_data(remove_pending=False))
transactions.to_csv('mint_transactions.csv')
```

but if I upgrade to 2.13 I get this error:
```
Traceback (most recent call last):
  File "C:/main.py", line 109, in <module>
    main()
  File "C:/main.py", line 102, in main
    get_mint_transactions()
  File "C:/main.py", line 36, in get_mint_transactions
    transactions = pd.DataFrame(client.get_transaction_data(remove_pending=False))
  File "C:\venv\lib\site-packages\mintapi\endpoints.py", line 575, in get_transaction_data
    data = self._get_transaction_data(json=payload.to_dict(), **kwargs)
  File "C:\venv\lib\site-packages\mintapi\endpoints.py", line 283, in _get_transaction_data
    return self.post(
  File "C:\venv\lib\site-packages\mintapi\endpoints.py", line 37, in post
    return self.request(method="POST", **kwargs)
  File "C:\venv\lib\site-packages\mintapi\browser.py", line 184, in request
    auth_headers = self._get_api_key_header()
  File "C:\venv\lib\site-packages\mintapi\browser.py", line 212, in _get_api_key_header
    api_key = self.driver.execute_script("return " + key_var)
AttributeError: 'NoneType' object has no attribute 'execute_script'
```

I also noticed that for some reason 'authenticator' was removed as a possible mfa-method. Not sure why this was removed as it worked perfectly fine for me pre-2.13. I tried mfa_method='soft-token' and tried removing the mfa_method altogether but still get the above error so not related but just pointing it out.

**Comment by ktorq** [comment]
Here is the new code for 2.13:

https://github.com/mintapi/mintapi/blob/c00def85b34e72ba099988e4ee35c02dbc024f71/mintapi/browser.py

```
 def _get_api_key_header(self):
        key_var = "window.__shellInternal.appExperience.appApiKey"
        api_key = self.driver.execute_script("return " + key_var)
        auth = "Intuit_APIKey intuit_apikey=" + api_key
        auth += ", intuit_apikey_version=1.0"
        header = {"authorization": auth}
        header.update(JSON_HEADER)
        return header
```

**Comment by MarcoCamilo** [comment]
Hi! I'm also experiencing the same problem. Below's the python script I've always used. 
```
mint = mintapi.Mint(
    user,
    password,
    mfa_method='email',
    intuit_account = None,
    headless = False,
    session_path = None,
    imap_account = None,
    imap_password = None,
    imap_server = None,
    imap_folder = 'INBOX',
    wait_for_sync=False, 
    wait_for_sync_timeout=300,
    use_chromedriver_on_path=False
)

mintData = mint.get_transaction_data(include_investment=False)

mint.close()
```

Here's the error I'm also getting:

```
Traceback (most recent call last):
  File "/Users/marco-andres/Documents/mint_script.py", line 26, in <module>
    mintData = mint.get_transaction_data(include_investment=False)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/mintapi/endpoints.py", line 575, in get_transaction_data
    data = self._get_transaction_data(json=payload.to_dict(), **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/mintapi/endpoints.py", line 283, in _get_transaction_data
    return self.post(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/mintapi/endpoints.py", line 37, in post
    return self.request(method="POST", **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/mintapi/browser.py", line 183, in request
    auth_headers = self._get_api_key_header()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/mintapi/browser.py", line 211, in _get_api_key_header
    api_key = self.driver.execute_script("return " + key_var)
AttributeError: 'NoneType' object has no attribute 'execute_script'
```

**Comment by matt199x** [comment]
Same issue:
`Traceback (most recent call last):
  File "/home/pi/BalanceUpdater-stripped.py", line 74, in <module>
    results = int(mint.get_net_worth_data())
  File "/usr/local/lib/python3.9/dist-packages/mintapi/endpoints.py", line 670, in get_net_worth_data
    data = self.get_trend_data(
  File "/usr/local/lib/python3.9/dist-packages/mintapi/endpoints.py", line 660, in get_trend_data
    return self._get_trend_data(json=payload.to_dict(), **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/mintapi/endpoints.py", line 299, in _get_trend_data
    return self.post(
  File "/usr/local/lib/python3.9/dist-packages/mintapi/endpoints.py", line 37, in post
    return self.request(method="POST", **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/mintapi/browser.py", line 184, in request
    auth_headers = self._get_api_key_header()
  File "/usr/local/lib/python3.9/dist-packages/mintapi/browser.py", line 212, in _get_api_key_header
    api_key = self.driver.execute_script("return " + key_var)
AttributeError: 'NoneType' object has no attribute 'execute_script'`

**Comment by TMcCode** [comment]
Seem to be having same issue here.

**Comment by mrooney** [comment]
Does reverting to 2.12 resolve the issue? I'm also curious if --use-rest-client (or use_rest_client=True to Mint() via Python) resolves it on 2.13

**Comment by MarcoCamilo** [comment]
I reverted to the previous version and worked like a charm 👍🏻

Marco-Andrés Camilo-Pietri

**Comment by matt199x** [comment]
> Does reverting to 2.12 resolve the issue? I'm also curious if --use-rest-client (or use_rest_client=True to Mint() via Python) resolves it on 2.13

I just reverted and it is working now.

**Comment by areagu** [comment]
this is happening for me as well.  so the master branch is broken then ? i must revert to prior version ?

**Comment by CalvinChanCan** [comment]
I was able to recreate the same issues as @ktorq and @MarcoCamilo  

In both the example scripts above (using the default browser based client), the Mint constructor is set up to pass the email and password using position arguments as expected in 2.12. However in 2.13, the positional arguments are now the [API key and cookies](https://github.com/mintapi/mintapi/blob/main/mintapi/api.py#L12) to use the new rest client. To resolve these issues, we can use keyword arguments. See examples below:

```
client = mintapi.Mint(email=keys['mint_user'], password=keys['mint_pw'], headless=False, wait_for_sync=False, mfa_method='authenticator')
```

```
mint = mintapi.Mint(
    email=user,
    password=password,
    mfa_method='email',
    intuit_account = None,
    headless = False,
    session_path = None,
    imap_account = None,
    imap_password = None,
    imap_server = None,
    imap_folder = 'INBOX',
    wait_for_sync=False, 
    wait_for_sync_timeout=300,
    use_chromedriver_on_path=False
)
```

Consequently, there are some other breaking changes in 2.13. The mint object new has a `browser` and `rest_client` to call the mint functions/endpoints. So if you're using the browser based client, you'll need to update `client.get_transaction_data` to `client.browser.get_transaction_data`

If you like to use the new rest client, that would resolve the above issues in 2.13
```
mint = mintapi.Mint(
    email=user,
    password=password,
    ...
    use_rest_client=True,
)

mint.rest_client.get_transaction_data()
```

Finally, I can open up a PR to update the readme to clarify these breaking changes for using the traditional browser based client.

**Comment by mrooney** [comment]
I just released 2.14 to pypi with #593 merged (thanks @CalvinChanCan!). Please let me know if that doesn't address the issue :)
